In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
dataset = pd.read_csv("cancer_data.csv")
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
dataset.shape

(569, 33)

**Define the features and the target**

In [11]:
x = dataset[['radius_mean','texture_mean','perimeter_mean','area_mean']]
y = dataset['diagnosis']

**Split the dataset into train and test using sklearn before building the SVM algorithm model**

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,x_train,y_test = train_test_split(x,y,test_size = 0.20)

**Import the support vector classifier function or SVC function from Sklearn SVM module. Build the Support Vector Machine model with the help of the SVC function**

In [15]:
from sklearn.svm import SVC
svclassifier = SVC(kernel = "linear")
svclassifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

**Predict values using the SVM algorithm model**

In [16]:
y_pred = svclassifier.predict(x_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[62  0]
 [ 8 44]]
              precision    recall  f1-score   support

           B       0.89      1.00      0.94        62
           M       1.00      0.85      0.92        52

    accuracy                           0.93       114
   macro avg       0.94      0.92      0.93       114
weighted avg       0.94      0.93      0.93       114



**Implementing Kernel SVM with Sklearn SVM module**

In [22]:
#kernel = 'poly'
from sklearn.svm import SVC
svclassifier1 = SVC(kernel='poly', degree = 8)
svclassifier1.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
y_pred1 = svclassifier1.predict(x_test)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[61  1]
 [15 37]]
              precision    recall  f1-score   support

           B       0.80      0.98      0.88        62
           M       0.97      0.71      0.82        52

    accuracy                           0.86       114
   macro avg       0.89      0.85      0.85       114
weighted avg       0.88      0.86      0.86       114



In [25]:
#kernel = 'Radial Basis Function'
from sklearn.svm import SVC
svclassifier2 = SVC(kernel='rbf', degree = 8)
svclassifier2.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
y_pred2 = svclassifier2.predict(x_test)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[61  1]
 [15 37]]
              precision    recall  f1-score   support

           B       0.80      0.98      0.88        62
           M       0.97      0.71      0.82        52

    accuracy                           0.86       114
   macro avg       0.89      0.85      0.85       114
weighted avg       0.88      0.86      0.86       114



In [28]:
#kernel = 'Sigmoid'
from sklearn.svm import SVC
svclassifier3 = SVC(kernel='sigmoid', degree = 8)
svclassifier3.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [29]:
y_pred3 = svclassifier3.predict(x_test)

In [30]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[40 22]
 [50  2]]
              precision    recall  f1-score   support

           B       0.44      0.65      0.53        62
           M       0.08      0.04      0.05        52

    accuracy                           0.37       114
   macro avg       0.26      0.34      0.29       114
weighted avg       0.28      0.37      0.31       114



**By comparing all the kernels LINEAR kernel gives better accuracy interms of seperating "Benign" and "Malignant"**

**THANK YOU.....!**